[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "local-ai-assistant"
version = "0.1.0"
description = "A local AI assistant powered by Ollama"
requires-python = ">=3.12"
dependencies = [
    "requests"
]


[tool.setuptools.packages.find]
where = ["src"]